name: human_grasp_pred
channels:
  - pytorch
  - conda-forge
dependencies:
  - addict=2.4.0
  - anyio=3.3.2
  - argon2-cffi=21.1.0
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.10.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=5.0.0
  - brotlipy=0.7.0
  - ca-certificates=2022.5.18.1
  - certifi=2021.5.30
  - cffi=1.14.6
  - charset-normalizer=2.0.12
  - colorama=0.4.4
  - contextvars=2.4
  - cryptography=35.0.0
  - cycler=0.11.0
  - dataclasses=0.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - freetype=2.10.4
  - icu=69.1
  - idna=3.3
  - ignite=0.3.0
  - immutables=0.16
  - importlib-metadata=4.8.1
  - intel-openmp
  - ipykernel=5.5.5
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.17.2
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.1.2
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.3
  - jupyter_core=4.8.1
  - jupyter_server=1.13.2
  - jupyterlab=3.3.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.1.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=13.0.1
  - libdeflate=1.10
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4  
  - mkl_fft=1.0.10  
  - nbclassic=0.3.5  
  - nbclient=0.5.9  
  - nbconvert=6.0.7  
  - nbformat=5.1.3  
  - nest-asyncio=1.5.5  
  - notebook=6.3.0  
  - numpy=1.19.5  
  - olefile=0.46  
  - openjpeg=2.4.0  
  - openssl=1.1.1o  
  - packaging=21.3  
  - pandas=1.1.5  
  - pandoc=2.18  
  - pandocfilters=1.5.0  
  - parso=0.7.1  
  - pickleshare=0.7.5  
  - pillow=8.3.2  
  - pip=21.3.1  
  - plyfile=0.7.4  
  - prometheus_client=0.14.1  
  - prompt-toolkit=3.0.29  
  - prompt_toolkit=3.0.29  
  - pycparser=2.21  
  - pygments=2.12.0  
  - pyopenssl=22.0.0  
  - pyparsing=3.0.9  
  - pyqt=5.12.3  
  - pyqt-impl=5.12.3  
  - pyqt5-sip=4.19.18  
  - pyqtchart=5.12  
  - pyqtwebengine=5.12.1  
  - pyrsistent=0.17.3  
  - pysocks=1.7.1    
  - pytorch=1.10.2  
  - pytz=2022.1   
  - pyyaml=5.4.1  
  - pyzmq=22.3.0  
  - qt=5.12.9  
  - qtconsole=5.2.2  
  - qtconsole-base=5.2.2  
  - qtpy=2.0.1  
  - requests=2.27.1  
  - scikit-learn=0.24.2  
  - scipy=1.5.3  
  - send2trash=1.8.0  
  - setuptools=58.0.4  
  - six=1.16.0  
  - sniffio=1.2.0  
  - sqlite=3.38.5  
  - tbb=2021.5.0  
  - terminado=0.12.1  
  - testpath=0.6.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchvision=0.2.1
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=4.3.3
  - trimesh=3.12.0
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - deprecation==2.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jupyter-packaging==0.10.6
    - open3d==0.15.2
    - tomlkit==0.10.2
    - torchfile==0.1.0
    - transforms3d==0.3.1
    - visdom==0.1.8.9